import {
  ProfileField,
  DocumentRow,
  ExtractedField,
  ServiceRow,
  ServiceRequirement,
  RequirementStatusRow,
} from '@/types';

export const DEFAULT_USER = {
  id: 'u0000000-0000-0000-0000-000000000001',
  email: 'sankeerths615@gmail.com',
  name: 'Sai Sankeerth',
  role: 'Applicant / Student',
  phone: '9876543210',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
};

export const INITIAL_SERVICES: ServiceRow[] = [
  {
    id: 's001',
    name: 'Post Matric Scholarship',
    description: 'Provided by Government of India. Central & State sponsored scholarship scheme for students pursuing post-secondary courses in recognized colleges and universities.',
    official_url: 'https://scholarships.gov.in',
    official_domain: 'scholarships.gov.in',
    category: 'Higher Education & Scholarships',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 's002',
    name: 'Pradhan Mantri Awas Yojana (PMAY-U)',
    description: 'Housing subsidy scheme for urban families.',
    official_url: 'https://pmaymis.gov.in',
    official_domain: 'pmaymis.gov.in',
    category: 'Housing & Urban Affairs',
    is_active: false,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 's003',
    name: 'Instant e-PAN Card Application',
    description: 'Paperless digital PAN issuance by Income Tax Department.',
    official_url: 'https://eportal.incometax.gov.in',
    official_domain: 'incometax.gov.in',
    category: 'Identity & Tax',
    is_active: false,
    created_at: '2026-01-01T00:00:00Z',
  },
];

// 9 Requirements for Post Matric Scholarship matching Screen 2, 6, 7
export const INITIAL_REQUIREMENTS: ServiceRequirement[] = [
  {
    id: 'req_01',
    service_id: 's001',
    requirement_type: 'IDENTITY_DOCUMENT',
    field_name: null,
    label: 'Aadhaar Card',
    required: true,
    guidance_text: 'Authority: UIDAI (myaadhaar.uidai.gov.in)\nValidity: Lifetime\n\nHow to get & prepare:\n1. Download digitally signed e-Aadhaar from myaadhaar.uidai.gov.in using your 12-digit UID and mobile OTP.\n2. Verify that your Full Name, Father Name, and DOB match your Class 10 Matriculation certificate character-by-character.\n3. Ensure your Aadhaar is actively seeded with your bank account for Direct Benefit Transfer (DBT) on the NPCI mapper.\n4. Save as a clear PDF/JPG under 200 KB.',
    notes: 'AADHAAR',
    display_order: 1,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_02',
    service_id: 's001',
    requirement_type: 'INCOME_DOCUMENT',
    field_name: null,
    label: 'Income Certificate',
    required: true,
    guidance_text: 'Authority: Revenue Department (Tahsildar / Mandal Revenue Officer - MRO)\nValidity: 1 Financial Year (Must be issued on or after April 1st of current financial year)\nTurnaround: 3 to 7 Working Days\n\nHow to get:\n1. Apply online via State Citizen Services (MeeSeva in Telangana/AP, e-District in Delhi/UP) or visit nearest CSC.\n2. Submit parent salary slip / Form 16 / Ration Card or notarized income affidavit.\n3. Village Revenue Officer (VRO) and Revenue Inspector conduct field verification.\n4. Tahsildar issues a digitally signed certificate with unique QR verification code.\n5. Certified annual income must be below ₹2,50,000 for full fee reimbursement.',
    notes: 'INCOME_CERTIFICATE',
    display_order: 2,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_03',
    service_id: 's001',
    requirement_type: 'EDUCATION_DOCUMENT',
    field_name: null,
    label: 'College ID',
    required: true,
    guidance_text: 'Authority: College Administration / Student Affairs Cell\nValidity: Current Academic Year 2025-26\n\nHow to prepare:\n1. Collect your official student identity card issued by your institution upon admission.\n2. Ensure your photo, Roll Number / Hall Ticket Number, Branch, and academic year are clearly legible.\n3. Scan both front and back sides on a single page in high resolution (150-200 DPI) under 200 KB.',
    notes: 'COLLEGE_ID',
    display_order: 3,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_04',
    service_id: 's001',
    requirement_type: 'EDUCATION_DOCUMENT',
    field_name: null,
    label: 'Bonafide Certificate',
    required: true,
    guidance_text: 'Authority: College Academic Registrar / Principal\'s Office\nValidity: Current Academic Year\nTurnaround: 1 - 2 Working Days\n\nHow to get:\n1. Visit the College Scholarship / Academic Section counter.\n2. Request the official Bonafide Certificate printed on College Letterhead.\n3. CRITICAL: The certificate MUST mention the College AISHE Code (e.g. C-19736), your Admission Roll No, and current Year/Sem.\n4. Obtain the physical signature of the Principal/Dean and the official institutional round seal.\n5. Scan as PDF under 200 KB.',
    notes: 'BONAFIDE_CERTIFICATE',
    display_order: 4,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_05',
    service_id: 's001',
    requirement_type: 'EDUCATION_DOCUMENT',
    field_name: null,
    label: 'Marksheet',
    required: true,
    guidance_text: 'Authority: State Intermediate Board / CBSE / University Controller of Examinations\nPortal: digilocker.gov.in\n\nHow to prepare:\n1. Download authentic digitally signed marks memo from DigiLocker or obtain original semester grade card.\n2. Must show passing status with minimum 50% aggregate in the previous qualifying examination.\n3. Student Name and Father\'s Name must match your Aadhaar card.',
    notes: 'MARKSHEET',
    display_order: 5,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_06',
    service_id: 's001',
    requirement_type: 'BANK_DOCUMENT',
    field_name: null,
    label: 'Bank Passbook',
    required: true,
    guidance_text: 'Authority: Nationalized / Scheduled Commercial Bank\nCritical Requirement: Aadhaar-NPCI Seeding for DBT (Causes 80% of rejections if missing!)\n\nHow to prepare:\n1. Account must be in the student\'s individual name (Joint accounts are rejected by PFMS).\n2. Visit your bank branch and submit the "NPCI Aadhaar Mandate Form (Annexure 1)" to activate DBT credit.\n3. Verify active status on myaadhaar.uidai.gov.in under "Bank Seeding Status".\n4. Scan the first page of passbook clearly showing Account Number, IFSC code, and Branch.',
    notes: 'BANK_PASSBOOK',
    display_order: 6,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_07',
    service_id: 's001',
    requirement_type: 'PERSONAL_INFORMATION',
    field_name: 'full_name',
    label: 'Full Name',
    required: true,
    guidance_text: 'Must match character-by-character with your matriculation certificate and Aadhaar card. Avoid using informal initials if your 10th certificate has the expanded name.',
    notes: null,
    display_order: 7,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_08',
    service_id: 's001',
    requirement_type: 'PERSONAL_INFORMATION',
    field_name: 'date_of_birth',
    label: 'Date of Birth',
    required: true,
    guidance_text: 'Date of birth recorded in 10th standard certificate (DD/MM/YYYY). Must be identical on both Aadhaar and educational records.',
    notes: null,
    display_order: 8,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'req_09',
    service_id: 's001',
    requirement_type: 'DECLARATION',
    field_name: null,
    label: 'Domicile Certificate',
    required: true,
    guidance_text: 'Authority: Revenue Department (Tahsildar / Sub-Divisional Magistrate)\nValidity: Permanent\nTurnaround: 5 - 10 Working Days\n\nHow to get:\n1. Apply through State e-District portal or MeeSeva center.\n2. Submit 5+ years residence proofs (Study certificates from Class 1 to 10, Ration Card, Electricity Bills).\n3. Revenue Inspector verifies residency records.\n4. Collect digitally signed Nativity/Domicile certificate with QR code.',
    notes: 'DOMICILE_CERTIFICATE',
    display_order: 9,
    created_at: '2026-01-01T00:00:00Z',
  },
];

// Document Vault Rows matching Screen 4
export const INITIAL_DOCUMENTS: DocumentRow[] = [
  {
    id: 'doc_aadhaar',
    user_id: DEFAULT_USER.id,
    document_type: 'AADHAAR',
    storage_path: 'vault/Aadhaar_Card.pdf',
    original_filename: 'Aadhaar_Card.pdf',
    mime_type: 'application/pdf',
    status: 'VERIFIED',
    ocr_raw_text: 'GOVERNMENT OF INDIA\nUnique Identification Authority of India\nName: Sai Sankeerth\nDOB: 15/08/2001\nGender: Male\nAadhaar No: 5492 8173 9012\nAddress: H.No 4-12/A, Gandhi Nagar, Hyderabad, Telangana - 500081',
    is_superseded: false,
    created_at: '2025-05-12T10:00:00Z',
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'doc_income',
    user_id: DEFAULT_USER.id,
    document_type: 'INCOME_CERTIFICATE',
    storage_path: 'vault/Income_Certificate.pdf',
    original_filename: 'Income_Certificate.pdf',
    mime_type: 'application/pdf',
    status: 'EXTRACTED',
    ocr_raw_text: 'GOVERNMENT REVENUE DEPARTMENT\nIncome Certificate No: IC2025-92831\nApplicant: Sai Sankeerth\nFather Name: Suresh Kumar\nAnnual Income: Rs. 180000\nIssue Date: 01/04/2025\nIssuing Authority: Tehsildar Office',
    is_superseded: false,
    created_at: '2025-05-11T14:30:00Z',
    updated_at: '2025-05-11T14:32:00Z',
  },
  {
    id: 'doc_college_id',
    user_id: DEFAULT_USER.id,
    document_type: 'COLLEGE_ID',
    storage_path: 'vault/College_ID.pdf',
    original_filename: 'College_ID.pdf',
    mime_type: 'application/pdf',
    status: 'VERIFIED',
    ocr_raw_text: 'VIDYA JYOTHI INSTITUTE OF TECHNOLOGY\nStudent Identity Card\nName: Sai Sankeerth\nRoll No: 22071A0589\nCourse: B.Tech Computer Science\nValid: 2022-2026',
    is_superseded: false,
    created_at: '2025-05-13T09:15:00Z',
    updated_at: '2025-05-13T09:18:00Z',
  },
  {
    id: 'doc_marksheet',
    user_id: DEFAULT_USER.id,
    document_type: 'MARKSHEET',
    storage_path: 'vault/Marksheet.pdf',
    original_filename: 'Marksheet.pdf',
    mime_type: 'application/pdf',
    status: 'UPLOADED',
    ocr_raw_text: 'CENTRAL BOARD OF SECONDARY EDUCATION\nClass XII Examination Certificate\nCandidate Name: SAI SANKEERTH\nResult: PASS (88.4%)',
    is_superseded: false,
    created_at: '2025-05-13T11:00:00Z',
    updated_at: '2025-05-13T11:02:00Z',
  },
  {
    id: 'doc_domicile',
    user_id: DEFAULT_USER.id,
    document_type: 'DOMICILE_CERTIFICATE',
    storage_path: 'vault/Domicile_Certificate.pdf',
    original_filename: 'Domicile_Certificate.pdf',
    mime_type: 'application/pdf',
    status: 'FAILED',
    ocr_raw_text: null,
    is_superseded: false,
    created_at: '2025-05-10T16:00:00Z',
    updated_at: '2025-05-10T16:01:00Z',
  },
];

// Extracted fields matching Screen 5 (Review Extracted Fields for Income Certificate)
export const INITIAL_EXTRACTED_FIELDS: ExtractedField[] = [
  {
    id: 'ef_inc_01',
    document_id: 'doc_income',
    field_name: 'full_name',
    raw_value: 'Sai Sankeerth',
    normalized_value: 'Sai Sankeerth',
    confidence: 0.98,
    accepted: false,
    created_at: '2025-05-11T14:32:00Z',
  },
  {
    id: 'ef_inc_02',
    document_id: 'doc_income',
    field_name: 'father_name',
    raw_value: 'Suresh Kumar',
    normalized_value: 'Suresh Kumar',
    confidence: 0.96,
    accepted: false,
    created_at: '2025-05-11T14:32:00Z',
  },
  {
    id: 'ef_inc_03',
    document_id: 'doc_income',
    field_name: 'annual_income',
    raw_value: '180000',
    normalized_value: '180000',
    confidence: 0.92,
    accepted: false,
    created_at: '2025-05-11T14:32:00Z',
  },
  {
    id: 'ef_inc_04',
    document_id: 'doc_income',
    field_name: 'issue_date',
    raw_value: '01/04/2025',
    normalized_value: '01/04/2025',
    confidence: 0.95,
    accepted: false,
    created_at: '2025-05-11T14:32:00Z',
  },
  {
    id: 'ef_inc_05',
    document_id: 'doc_income',
    field_name: 'issuing_authority',
    raw_value: 'Tehsildar Office',
    normalized_value: 'Tehsildar Office',
    confidence: 0.88,
    accepted: false,
    created_at: '2025-05-11T14:32:00Z',
  },
];

// Profile Fields matching Screen 3
export const INITIAL_PROFILE_FIELDS: ProfileField[] = [
  {
    id: 'pf_01',
    user_id: DEFAULT_USER.id,
    field_name: 'full_name',
    value: 'Sai Sankeerth',
    source_document_id: 'doc_aadhaar',
    confidence: 0.99,
    verified: true,
    confirmed_at: '2025-05-12T10:05:00Z',
    created_at: '2025-05-12T10:05:00Z',
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'pf_02',
    user_id: DEFAULT_USER.id,
    field_name: 'date_of_birth',
    value: '2001-08-15',
    source_document_id: 'doc_aadhaar',
    confidence: 0.98,
    verified: true,
    confirmed_at: '2025-05-12T10:05:00Z',
    created_at: '2025-05-12T10:05:00Z',
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'pf_03',
    user_id: DEFAULT_USER.id,
    field_name: 'phone_number',
    value: '9876543210',
    source_document_id: null,
    confidence: null,
    verified: true,
    confirmed_at: '2025-05-12T10:05:00Z',
    created_at: '2025-05-12T10:05:00Z',
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'pf_04',
    user_id: DEFAULT_USER.id,
    field_name: 'email',
    value: 'sankeerths615@gmail.com',
    source_document_id: null,
    confidence: null,
    verified: true,
    confirmed_at: '2025-05-12T10:05:00Z',
    created_at: '2025-05-12T10:05:00Z',
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'pf_05',
    user_id: DEFAULT_USER.id,
    field_name: 'annual_income',
    value: '180000',
    source_document_id: 'doc_income',
    confidence: 0.92,
    verified: true,
    confirmed_at: '2025-05-12T10:05:00Z',
    created_at: '2025-05-12T10:05:00Z',
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'pf_06',
    user_id: DEFAULT_USER.id,
    field_name: 'college_name',
    value: 'National Institute of Technology',
    source_document_id: 'doc_college_id',
    confidence: 0.95,
    verified: true,
    confirmed_at: '2025-05-13T09:18:00Z',
    created_at: '2025-05-13T09:18:00Z',
    updated_at: '2025-05-13T09:18:00Z',
  },
];

// Requirement Status matching Screen 2, 6, 7, 8 (67% Readiness Score: 6 Satisfied, 3 Missing, 1 Manually Resolved)
export const INITIAL_REQUIREMENT_STATUS: RequirementStatusRow[] = [
  {
    id: 'rs_01',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_01', // Aadhaar Card
    status: 'SATISFIED',
    satisfied_by_document_id: 'doc_aadhaar',
    satisfied_by_field_name: null,
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'rs_02',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_02', // Income Certificate
    status: 'SATISFIED',
    satisfied_by_document_id: 'doc_income',
    satisfied_by_field_name: null,
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'rs_03',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_03', // College ID
    status: 'SATISFIED',
    satisfied_by_document_id: 'doc_college_id',
    satisfied_by_field_name: null,
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-13T09:18:00Z',
  },
  {
    id: 'rs_04',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_04', // Bonafide Certificate
    status: 'MISSING',
    satisfied_by_document_id: null,
    satisfied_by_field_name: null,
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-13T10:00:00Z',
  },
  {
    id: 'rs_05',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_05', // Marksheet
    status: 'SATISFIED',
    satisfied_by_document_id: 'doc_marksheet',
    satisfied_by_field_name: null,
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-13T11:02:00Z',
  },
  {
    id: 'rs_06',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_06', // Bank Passbook
    status: 'MISSING',
    satisfied_by_document_id: null,
    satisfied_by_field_name: null,
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-13T10:00:00Z',
  },
  {
    id: 'rs_07',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_07', // Full Name
    status: 'SATISFIED',
    satisfied_by_document_id: null,
    satisfied_by_field_name: 'full_name',
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'rs_08',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_08', // Date of Birth
    status: 'SATISFIED',
    satisfied_by_document_id: null,
    satisfied_by_field_name: 'date_of_birth',
    resolved_note: null,
    locked: false,
    updated_at: '2025-05-12T10:05:00Z',
  },
  {
    id: 'rs_09',
    user_id: DEFAULT_USER.id,
    requirement_id: 'req_09', // Domicile Certificate
    status: 'MANUALLY_RESOLVED',
    satisfied_by_document_id: null,
    satisfied_by_field_name: null,
    resolved_note: 'Aadhaar residence address fulfills local domicile criteria.',
    locked: true,
    updated_at: '2025-05-13T10:00:00Z',
  },
];
