import {
  PanApplicationRecord,
  AuditLogRecord,
  ExceptionRecord,
  ConnectorRequestRecord,
} from "@/types/government";

export function getInitialPanApplications(): PanApplicationRecord[] {
  const baseTime = new Date().toISOString();

  return [
    {
      id: "PAN-2026-0001",
      userId: "u_0bc5a3b6-f059-4ab2-9870-46a9c25178b7",
      serviceId: "s003",
      serviceName: "Instant e-PAN & Physical Card Issuance",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Sai Sankeerth",
      applicantEmail: "sankeerths615@gmail.com",
      applicantPhone: "1234567890",
      stage: "OFFICER_REVIEW",
      status: "ACTION_REQUIRED",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Sai Sankeerth",
        fatherName: "Suresh Kumar",
        dateOfBirth: "2004-07-23",
        gender: "Male",
        mobile: "1234567890",
        email: "sankeerths615@gmail.com",
        aadhaarNumber: "123456789876",
        address: "H.No 4-12/A, Gandhi Nagar, Gachibowli",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500081",
      },
      documents: {
        identityProof: {
          name: "Aadhaar_Card_Verified.pdf",
          type: "AADHAAR",
          status: "VERIFIED",
          note: "Digitally signed e-Aadhaar from UIDAI",
        },
        dobProof: {
          name: "Class_10_Matriculation_Memo.pdf",
          type: "MARKSHEET",
          status: "VERIFIED",
          note: "DigiLocker verified CBSE record",
        },
        addressProof: {
          name: "Electricity_Bill_Utility.pdf",
          type: "DOMICILE_CERTIFICATE",
          status: "VERIFIED",
          note: "TSSPDCL utility bill within 3 months",
        },
      },
      verifications: [
        {
          id: "v1",
          name: "Identity Registry (UIDAI)",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Exact character-by-character match across application and Aadhaar identity registry.",
          timestamp: "2026-09-09T14:04:12Z",
          applicationValue: "Sai Sankeerth",
          registryValue: "Sai Sankeerth",
        },
        {
          id: "v2",
          name: "Date of Birth Verification",
          source: "DigiLocker CBSE Class 10 Record",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "DOB 2004-07-23 matches across UIDAI registry and educational records.",
          timestamp: "2026-09-09T14:04:15Z",
          applicationValue: "2004-07-23",
          registryValue: "2004-07-23",
          documentValue: "2004-07-23",
        },
        {
          id: "v3",
          name: "Aadhaar Seeding & Checksum",
          source: "UIDAI Verhoeff Checksum Engine",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "12-digit Aadhaar UID mathematically verified via Verhoeff checksum; active status confirmed.",
          timestamp: "2026-09-09T14:04:20Z",
          applicationValue: "1234 5678 9876",
          registryValue: "1234 5678 9876",
        },
        {
          id: "v4",
          name: "Postal Route & PIN Validation",
          source: "Department of Posts PIN Mapping Service",
          status: "VERIFIED",
          matchScore: 0.98,
          details: "PIN Code 500081 matches postal division Hyderabad, Telangana. Delivery route active.",
          timestamp: "2026-09-09T14:04:25Z",
          applicationValue: "H.No 4-12/A, Gandhi Nagar, PIN: 500081",
          registryValue: "Gachibowli SO, Division Hyderabad South",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation under Income Tax Act 1961 and Digital Personal Data Protection Act 2023.",
        legalAct: "Section 139A Income Tax Act & Section 6 DPDP Act 2023",
        consentId: "CNS-2026-9901-SAI",
        timestamp: "2026-09-09T14:02:10Z",
        ipAddress: "157.48.12.89",
      },
      physicalCard: {},
      aiSummary: {
        status: "OPTIMAL",
        summary: "All required citizen data and verified credentials are present. Identity verified via UIDAI e-KYC with 100% confidence. No duplicate PAN detected in NSDL/UTIITSL databases. Cross-system values match character-by-character.",
        detectedIssues: [],
        suggestedAction: "Case is complete and ready for statutory decision. Recommended action: Accept Application.",
        confidenceScore: 0.99,
        disclaimer: "AI CANNOT automatically approve or reject. AI provides evidence synthesis; final legal determination rests solely with the authorized Department Officer.",
      },
      createdAt: "2026-09-09T14:00:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0002",
      userId: "u_demo_anjali",
      serviceId: "s003",
      serviceName: "Instant e-PAN & Physical Card Issuance",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, New Delhi",
      applicantName: "Anjali Sharma",
      applicantEmail: "anjali.sharma@example.com",
      applicantPhone: "9876501234",
      stage: "VERIFICATION_IN_PROGRESS",
      status: "API_UNAVAILABLE",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Anjali Sharma",
        fatherName: "Ramesh Sharma",
        dateOfBirth: "2002-11-18",
        gender: "Female",
        mobile: "9876501234",
        email: "anjali.sharma@example.com",
        aadhaarNumber: "889977665544",
        address: "Flat 204, Rosewood Apts, Sector 14",
        city: "Gurugram",
        state: "Haryana",
        pincode: "122001",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Birth_Certificate.pdf", type: "MARKSHEET", status: "PENDING" },
        addressProof: { name: "Voter_ID.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v2_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity matched with UIDAI e-KYC token.",
          timestamp: "2026-09-09T14:15:00Z",
        },
        {
          id: "v2_2",
          name: "PAN Core Verification Service",
          source: "CBDT PAN Core Engine Gateway",
          status: "FAILED",
          matchScore: 0.0,
          details: "Gateway Timeout (504): External PAN core deduplication service did not respond within 5000ms. Queued for automatic retry.",
          timestamp: "2026-09-09T14:16:30Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation under Income Tax Act 1961 and DPDP Act 2023.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-9902-ANJ",
        timestamp: "2026-09-09T14:12:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "ATTENTION_NEEDED",
        summary: "Pre-flight validation passed. The downstream external PAN Core deduplication service timed out. Application retained safely in state without data loss; retry queue active.",
        detectedIssues: ["Downstream Service Unavailability: CBDT Core Engine Gateway (REQ-9002)"],
        suggestedAction: "Trigger manual connector retry or await automated 15-minute exponential backoff.",
        confidenceScore: 0.75,
        disclaimer: "AI CANNOT bypass external system verification prerequisites.",
      },
      createdAt: "2026-09-09T14:10:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0003",
      userId: "u_demo_rahul",
      serviceId: "s003",
      serviceName: "Instant e-PAN & Physical Card Issuance",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Mumbai",
      applicantName: "Rahul Verma",
      applicantEmail: "rahul.verma@example.com",
      applicantPhone: "9123456780",
      stage: "GOVERNMENT_PROCESSING",
      status: "VERIFICATION_CONFLICT",
      priority: "URGENT",
      slaDeadline: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Rahul Verma",
        fatherName: "Kishore Verma",
        dateOfBirth: "1999-05-14",
        gender: "Male",
        mobile: "9123456780",
        email: "rahul.verma@example.com",
        aadhaarNumber: "776655443322",
        address: "B-12, Green Park Avenue, Andheri East",
        city: "Mumbai",
        state: "Maharashtra",
        pincode: "400069",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Class_10_Certificate.pdf", type: "MARKSHEET", status: "FLAGGED" },
        addressProof: { name: "Passport_Copy.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v3_1",
          name: "Full Name Verification",
          source: "UIDAI Aadhaar Registry",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Name matches UIDAI registry.",
          timestamp: "2026-09-09T14:20:00Z",
          applicationValue: "Rahul Verma",
          registryValue: "Rahul Verma",
        },
        {
          id: "v3_2",
          name: "Date of Birth Cross-Source Validation",
          source: "Cross-System Registry & Document Comparator",
          status: "CONFLICT",
          matchScore: 0.0,
          details: "CRITICAL MISMATCH: Application submitted DOB 1999-05-14; UIDAI Aadhaar registry records 2000-05-14; Secondary School certificate records 1999-05-14.",
          timestamp: "2026-09-09T14:21:00Z",
          applicationValue: "1999-05-14",
          registryValue: "2000-05-14",
          documentValue: "1999-05-14",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-9903-RAH",
        timestamp: "2026-09-09T14:18:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "CRITICAL_MISMATCH",
        summary: "DOB Conflict detected: Source systems contain conflicting DOB values. Formly has explicitly flagged the conflict rather than arbitrarily deciding which source is correct. Human officer review is required.",
        detectedIssues: [
          "Discrepancy: Application DOB (1999-05-14) ≠ Aadhaar Registry DOB (2000-05-14)",
          "Requires officer adjudication of physical Class 10 certificate vs UIDAI database",
        ],
        suggestedAction: "Manual Review Required: Officer must review secondary Class 10 gazetted memo or return for citizen correction.",
        confidenceScore: 0.4,
        disclaimer: "Formly does NOT silently pick one source. Officer must make explicit determination.",
      },
      createdAt: "2026-09-09T14:18:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0004",
      userId: "u_demo_priya",
      serviceId: "s003",
      serviceName: "Instant e-PAN & Physical Card Issuance",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Bengaluru",
      applicantName: "Priya Patel",
      applicantEmail: "priya.patel@example.com",
      applicantPhone: "9012345678",
      stage: "OFFICER_REVIEW",
      status: "RETURNED_FOR_CORRECTION",
      priority: "NORMAL",
      slaDeadline: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      correctionReason: "Address proof image is partially cropped; house number and street name are illegible. Please upload a clear uncropped copy of your electricity bill or bank passbook.",
      data: {
        fullName: "Priya Patel",
        fatherName: "Mahesh Patel",
        dateOfBirth: "2003-03-22",
        gender: "Female",
        mobile: "9012345678",
        email: "priya.patel@example.com",
        aadhaarNumber: "665544332211",
        address: "Plot 45, Indiranagar 2nd Stage",
        city: "Bengaluru",
        state: "Karnataka",
        pincode: "560038",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Birth_Certificate.pdf", type: "MARKSHEET", status: "VERIFIED" },
        addressProof: {
          name: "Cropped_Bill.pdf",
          type: "DOMICILE_CERTIFICATE",
          status: "FLAGGED",
          note: "Rejected by officer: Illegible house number",
        },
      },
      verifications: [
        {
          id: "v4_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified with UIDAI.",
          timestamp: "2026-09-09T14:25:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-9904-PRI",
        timestamp: "2026-09-09T14:22:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "ATTENTION_NEEDED",
        summary: "Officer returned application for correction. Waiting for citizen to re-upload clear address proof document.",
        detectedIssues: ["Citizen action required: Upload legible address proof"],
        suggestedAction: "Waiting for citizen correction resubmission",
        confidenceScore: 0.8,
        disclaimer: "Once citizen submits updated address proof, system will automatically revalidate and place back in Officer Queue.",
      },
      createdAt: "2026-09-09T14:22:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0086",
      userId: "u_demo_citizen2",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Test Citizen Two",
      applicantEmail: "citizen.two@example.com",
      applicantPhone: "9876543210",
      stage: "GOVERNMENT_PROCESSING",
      status: "PROCESSING",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Test Citizen Two",
        fatherName: "Father Citizen",
        dateOfBirth: "1998-04-12",
        gender: "Male",
        mobile: "9876543210",
        email: "citizen.two@example.com",
        aadhaarNumber: "998877665544",
        address: "12-4B, Banjara Hills Road No 10",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500034",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Birth_Certificate.pdf", type: "MARKSHEET", status: "VERIFIED" },
        addressProof: { name: "Electricity_Bill.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v86_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified via UIDAI e-KYC.",
          timestamp: "2026-09-10T10:30:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0086",
        timestamp: "2026-09-10T10:25:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "OPTIMAL",
        summary: "Automated verification complete. Government core processing in progress.",
        detectedIssues: [],
        suggestedAction: "Awaiting gateway fulfillment",
        confidenceScore: 0.95,
        disclaimer: "AI verified preliminary format.",
      },
      createdAt: "2026-09-10T10:30:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0085",
      userId: "u_demo_citizen1",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Test Citizen One",
      applicantEmail: "citizen.one@example.com",
      applicantPhone: "9876543211",
      stage: "GOVERNMENT_PROCESSING",
      status: "PROCESSING",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Test Citizen One",
        fatherName: "Father Citizen",
        dateOfBirth: "1997-08-20",
        gender: "Female",
        mobile: "9876543211",
        email: "citizen.one@example.com",
        aadhaarNumber: "887766554433",
        address: "45-C, Madhapur Main Road",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500081",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Class_10_Memo.pdf", type: "MARKSHEET", status: "VERIFIED" },
        addressProof: { name: "Bank_Passbook.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v85_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified via UIDAI e-KYC.",
          timestamp: "2026-09-10T09:15:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0085",
        timestamp: "2026-09-10T09:10:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "OPTIMAL",
        summary: "Automated verification complete. Government core processing in progress.",
        detectedIssues: [],
        suggestedAction: "Awaiting gateway fulfillment",
        confidenceScore: 0.95,
        disclaimer: "AI verified preliminary format.",
      },
      createdAt: "2026-09-10T09:15:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0081",
      userId: "u_demo_sai_complete",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Sai Sankeerth",
      applicantEmail: "sai.completed@example.com",
      applicantPhone: "9876543212",
      stage: "DELIVERED",
      status: "COMPLETED",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Sai Sankeerth",
        fatherName: "Suresh Kumar",
        dateOfBirth: "2004-07-23",
        gender: "Male",
        mobile: "9876543212",
        email: "sai.completed@example.com",
        aadhaarNumber: "123456789876",
        address: "H.No 4-12/A, Gandhi Nagar, Gachibowli",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500081",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "CBSE_Certificate.pdf", type: "MARKSHEET", status: "VERIFIED" },
        addressProof: { name: "Electricity_Bill.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v81_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified via UIDAI e-KYC.",
          timestamp: "2026-09-09T11:00:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0081",
        timestamp: "2026-09-09T10:50:00Z",
      },
      physicalCard: {
        panNumber: "CHYPS5054Y",
        printedAt: "2026-09-09T12:00:00Z",
        dispatchPartner: "India Post (Speed Post)",
        trackingNumber: "IN51772763IN",
        deliveredAt: "2026-09-09T16:30:00Z",
      },
      aiSummary: {
        status: "OPTIMAL",
        summary: "Fulfillment complete. Physical PAN PVC card delivered to applicant.",
        detectedIssues: [],
        suggestedAction: "Case closed",
        confidenceScore: 1.0,
        disclaimer: "Delivered via India Post Speed Post.",
      },
      createdAt: "2026-09-09T11:00:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0082",
      userId: "u_demo_anjali_complete",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Anjali Sharma",
      applicantEmail: "anjali.completed@example.com",
      applicantPhone: "9876543213",
      stage: "DELIVERED",
      status: "COMPLETED",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Anjali Sharma",
        fatherName: "Ramesh Sharma",
        dateOfBirth: "2002-11-18",
        gender: "Female",
        mobile: "9876543213",
        email: "anjali.completed@example.com",
        aadhaarNumber: "889977665544",
        address: "Flat 204, Rosewood Apts",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500032",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Birth_Certificate.pdf", type: "MARKSHEET", status: "VERIFIED" },
        addressProof: { name: "Voter_ID.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v82_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified via UIDAI e-KYC.",
          timestamp: "2026-09-09T12:00:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0082",
        timestamp: "2026-09-09T11:50:00Z",
      },
      physicalCard: {
        panNumber: "BKWPS4910K",
        printedAt: "2026-09-09T13:00:00Z",
        dispatchPartner: "India Post (Speed Post)",
        trackingNumber: "IN88291034IN",
        deliveredAt: "2026-09-09T17:15:00Z",
      },
      aiSummary: {
        status: "OPTIMAL",
        summary: "Fulfillment complete. Physical card handed over to recipient.",
        detectedIssues: [],
        suggestedAction: "Case closed",
        confidenceScore: 1.0,
        disclaimer: "Delivered via India Post Speed Post.",
      },
      createdAt: "2026-09-09T12:00:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0083",
      userId: "u_demo_rahul_rej",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Rahul Verma",
      applicantEmail: "rahul.rejected@example.com",
      applicantPhone: "9876543214",
      stage: "OFFICER_REVIEW",
      status: "REJECTED",
      priority: "URGENT",
      slaDeadline: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      rejectionReason: "Incurable demographic discrepancy across identity repositories. Applicant failed to provide certified proof of birth within statutory period under Section 139A.",
      data: {
        fullName: "Rahul Verma",
        fatherName: "Kishore Verma",
        dateOfBirth: "1999-05-14",
        gender: "Male",
        mobile: "9876543214",
        email: "rahul.rejected@example.com",
        aadhaarNumber: "776655443322",
        address: "B-12, Green Park Avenue",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500016",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Class_10_Certificate.pdf", type: "MARKSHEET", status: "FLAGGED" },
        addressProof: { name: "Passport_Copy.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v83_1",
          name: "Date of Birth Validation",
          source: "Cross-System Registry Comparator",
          status: "FAILED",
          matchScore: 0.0,
          details: "Conflict unresolvable.",
          timestamp: "2026-09-09T13:45:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0083",
        timestamp: "2026-09-09T13:40:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "CRITICAL_MISMATCH",
        summary: "Officer evaluated evidence and confirmed rejection under Section 139A statutory rules.",
        detectedIssues: ["Incurable discrepancy in date of birth record"],
        suggestedAction: "Application closed as rejected",
        confidenceScore: 1.0,
        disclaimer: "Legal decision taken by authorized Officer Sai Sankeerth.",
      },
      createdAt: "2026-09-09T13:45:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0084",
      userId: "u_demo_priya_act",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Priya Patel",
      applicantEmail: "priya.review@example.com",
      applicantPhone: "9876543215",
      stage: "OFFICER_REVIEW",
      status: "ACTION_REQUIRED",
      priority: "NORMAL",
      slaDeadline: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Priya Patel",
        fatherName: "Mahesh Patel",
        dateOfBirth: "2003-03-22",
        gender: "Female",
        mobile: "9876543215",
        email: "priya.review@example.com",
        aadhaarNumber: "665544332211",
        address: "Plot 45, Indiranagar 2nd Stage",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500038",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Birth_Certificate.pdf", type: "MARKSHEET", status: "VERIFIED" },
        addressProof: { name: "Electricity_Bill_Resubmitted.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v84_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified via UIDAI e-KYC.",
          timestamp: "2026-09-08T15:20:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0084",
        timestamp: "2026-09-08T15:10:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "OPTIMAL",
        summary: "Citizen uploaded updated clear address proof. Case ready for final officer approval.",
        detectedIssues: [],
        suggestedAction: "Officer Review: Approve corrected application",
        confidenceScore: 0.98,
        disclaimer: "Final statutory determination rests with the officer.",
      },
      createdAt: "2026-09-08T15:20:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0078",
      userId: "u_demo_ext_mismatch",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "External system mismatch",
      applicantEmail: "system.mismatch@example.com",
      applicantPhone: "9876543216",
      stage: "GOVERNMENT_PROCESSING",
      status: "VERIFICATION_CONFLICT",
      priority: "HIGH",
      slaDeadline: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Sunita Reddy",
        fatherName: "Venkatesh Reddy",
        dateOfBirth: "1995-10-10",
        gender: "Female",
        mobile: "9876543216",
        email: "system.mismatch@example.com",
        aadhaarNumber: "554433221100",
        address: "Lane 3, Jubilee Hills",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "500033",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "PAN_NSDL_Record.pdf", type: "MARKSHEET", status: "FLAGGED" },
        addressProof: { name: "Voter_ID.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v78_1",
          name: "CBDT PAN Core Engine Gateway",
          source: "NSDL Core Database",
          status: "CONFLICT",
          matchScore: 0.5,
          details: "External system reports potential existing PAN match under similar name and DOB.",
          timestamp: "2026-09-08T10:00:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0078",
        timestamp: "2026-09-08T09:50:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "CRITICAL_MISMATCH",
        summary: "External system reports existing PAN record conflict. Officer adjudication required before issuance.",
        detectedIssues: ["Potential duplicate PAN match in NSDL core system"],
        suggestedAction: "Officer adjudication required",
        confidenceScore: 0.65,
        disclaimer: "Requires officer verification of biometric records.",
      },
      createdAt: "2026-09-08T10:00:00Z",
      updatedAt: baseTime,
    },
    {
      id: "PAN-2026-0074",
      userId: "u_demo_oldest_pending",
      serviceId: "s003",
      serviceName: "Instant e-PAN",
      department: "Income Tax Department (CBDT) - PAN Division",
      office: "Regional Processing Cell, Hyderabad",
      applicantName: "Oldest Pending Applicant",
      applicantEmail: "oldest.pending@example.com",
      applicantPhone: "9876543217",
      stage: "VERIFICATION_IN_PROGRESS",
      status: "PROCESSING",
      priority: "NORMAL",
      slaDeadline: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
      assignedOfficerId: "OFF-PAN-7042",
      assignedOfficerName: "Officer Sai Sankeerth",
      data: {
        fullName: "Vikram Sethi",
        fatherName: "Anand Sethi",
        dateOfBirth: "1992-01-15",
        gender: "Male",
        mobile: "9876543217",
        email: "oldest.pending@example.com",
        aadhaarNumber: "443322110099",
        address: "Sector 7, Alwal",
        city: "Secunderabad",
        state: "Telangana",
        pincode: "500010",
      },
      documents: {
        identityProof: { name: "Aadhaar_Card.pdf", type: "AADHAAR", status: "VERIFIED" },
        dobProof: { name: "Matriculation.pdf", type: "MARKSHEET", status: "PENDING" },
        addressProof: { name: "Electricity_Bill.pdf", type: "DOMICILE_CERTIFICATE", status: "VERIFIED" },
      },
      verifications: [
        {
          id: "v74_1",
          name: "UIDAI Aadhaar Registry",
          source: "Aadhaar e-KYC 2.5 API",
          status: "VERIFIED",
          matchScore: 1.0,
          details: "Identity verified via UIDAI e-KYC.",
          timestamp: "2026-09-03T09:00:00Z",
        },
      ],
      consent: {
        granted: true,
        purpose: "Statutory identity verification and PAN generation.",
        legalAct: "Section 139A Income Tax Act",
        consentId: "CNS-2026-0074",
        timestamp: "2026-09-03T08:50:00Z",
      },
      physicalCard: {},
      aiSummary: {
        status: "ATTENTION_NEEDED",
        summary: "7 days pending in verification queue. External education board certificate verification awaiting response.",
        detectedIssues: ["SLA breached - 7 days pending"],
        suggestedAction: "Trigger manual verification bypass or contact issuing board",
        confidenceScore: 0.7,
        disclaimer: "Flagged in SLA performance monitor.",
      },
      createdAt: "2026-09-03T09:00:00Z",
      updatedAt: baseTime,
    },
  ];
}

export function getInitialAuditLogs(): AuditLogRecord[] {
  return [
    {
      id: "AUD-9001",
      applicationId: "PAN-2026-0001",
      timestamp: "2026-09-09T14:02:10Z",
      actor: { id: "u_0bc5a3b6", name: "Sai Sankeerth", role: "CITIZEN" },
      action: "APPLICATION_SUBMITTED",
      stage: "SUBMITTED",
      source: "Citizen Portal",
      target: "Formly Orchestration Hub",
      purpose: "Statutory PAN card issuance application",
      consentToken: "CNS-2026-9901-SAI",
      result: "SUCCESS",
      details: "Application received and signed with citizen consent token.",
      requestId: "REQ-9001",
      tamperHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    },
    {
      id: "AUD-9002",
      applicationId: "PAN-2026-0001",
      timestamp: "2026-09-09T14:03:00Z",
      actor: { id: "SYS_ENGINE", name: "Consent Manager", role: "SYSTEM_WORKFLOW" },
      action: "CONSENT_VALIDATED",
      stage: "VALIDATING",
      source: "Consent Hub",
      target: "Data Protection Registry",
      purpose: "DPDP Act 2023 Section 6 compliance verification",
      consentToken: "CNS-2026-9901-SAI",
      result: "SUCCESS",
      details: "Citizen consent verified as free, specific, informed, unconditional, and unambiguous.",
      requestId: "REQ-9002",
      tamperHash: "8f481f3d8a1c6a7e08ef8b0f8e3f946e3134e7cb8a9926a31c5188f6b8b09341",
    },
    {
      id: "AUD-9003",
      applicationId: "PAN-2026-0001",
      timestamp: "2026-09-09T14:04:12Z",
      actor: { id: "SYS_CONNECTOR", name: "UIDAI e-KYC Connector", role: "CONNECTOR_JOB" },
      action: "IDENTITY_VERIFIED",
      stage: "VERIFICATION_IN_PROGRESS",
      source: "UIDAI Aadhaar Registry",
      target: "Formly Interoperability Layer",
      purpose: "Aadhaar e-KYC identity authentication",
      consentToken: "CNS-2026-9901-SAI",
      result: "SUCCESS",
      details: "100% biometric demographic match for Sai Sankeerth. Verhoeff checksum valid.",
      requestId: "REQ-9003",
      tamperHash: "3295c76acbf4caaed33c36b1b5fc9282cd50561f",
    },
    {
      id: "AUD-9004",
      applicationId: "PAN-2026-0001",
      timestamp: "2026-09-09T14:05:00Z",
      actor: { id: "SYS_ROUTER", name: "Government Routing Engine", role: "SYSTEM_WORKFLOW" },
      action: "OFFICER_ASSIGNED",
      stage: "OFFICER_ASSIGNED",
      source: "Department Queue Engine",
      target: "Officer Review Desk",
      purpose: "Workload distribution to authorized PAN verifier",
      result: "SUCCESS",
      details: "Assigned to Department Officer Sai Sankeerth (RPC Hyderabad) according to jurisdiction rules.",
      requestId: "REQ-9004",
      tamperHash: "b3f619e071e62bb08a1012674e1d5294",
    },
    {
      id: "AUD-9005",
      applicationId: "PAN-2026-0001",
      timestamp: "2026-09-09T14:21:00Z",
      actor: { id: "OFF-PAN-7042", name: "Officer Sai Sankeerth", role: "OFFICER" },
      action: "OFFICER_OPENED_WORKSPACE",
      stage: "OFFICER_REVIEW",
      source: "Government Operations Portal",
      target: "PAN Application Workspace",
      purpose: "Statutory review of verified case credentials",
      result: "SUCCESS",
      details: "Officer opened PAN-2026-0001 workspace and reviewed AI synthesis and cross-system comparison.",
      requestId: "REQ-9005",
      tamperHash: "0a5ef36b8c19a2e3f4b5c6d7e8f9a0b1",
    },
  ];
}

export function getInitialExceptions(): ExceptionRecord[] {
  return [
    {
      id: "EXC-101",
      severity: "CRITICAL",
      title: "API Gateway Timeout (504)",
      applicationId: "PAN-2026-0002",
      systemName: "PAN Core Deduplication Gateway (CBDT/NSDL)",
      timestamp: "2026-09-09T14:16:30Z",
      whatHappened: "Downstream external PAN deduplication service failed to return an acknowledgement within the configured 5000ms SLA timeout.",
      whyItHappened: "Upstream gateway network congestion at central CBDT processing node.",
      currentState: "VERIFICATION_IN_PROGRESS / API_UNAVAILABLE",
      autoRetry: true,
      retryAttempts: 1,
      humanActionRequired: "System is performing exponential backoff retry. Officer can trigger immediate retry if node is reported restored.",
      isResolved: false,
    },
    {
      id: "EXC-102",
      severity: "MANUAL_REVIEW",
      title: "Cross-System Date of Birth Discrepancy",
      applicationId: "PAN-2026-0003",
      systemName: "Cross-Source Comparator (UIDAI vs DigiLocker)",
      timestamp: "2026-09-09T14:21:00Z",
      whatHappened: "Citizen entered 1999-05-14; UIDAI database contains 2000-05-14. Formly flagged discrepancy for human decision.",
      whyItHappened: "Discrepancy exists in source government databases. Automated engine cannot silently select one record over another.",
      currentState: "GOVERNMENT_PROCESSING / VERIFICATION_CONFLICT",
      autoRetry: false,
      retryAttempts: 0,
      humanActionRequired: "Department Officer must review original Class 10 memo and adjudicate valid legal DOB or issue correction notice.",
      isResolved: false,
    },
    {
      id: "EXC-103",
      severity: "DELAYED",
      title: "Printing Batch Dispatch Congestion",
      applicationId: "PAN-2026-0014",
      systemName: "ISP Nashik Printing Service",
      timestamp: "2026-09-09T13:45:00Z",
      whatHappened: "Consignment batch packaging delayed by 18 minutes past typical 60-minute dispatch threshold.",
      whyItHappened: "High volume batch queue at Western Circle Printing Division.",
      currentState: "CARD_PRINTING",
      autoRetry: true,
      retryAttempts: 2,
      humanActionRequired: "Monitor queue depth. No citizen action required.",
      isResolved: false,
    },
  ];
}

export function getInitialConnectorRequests(): ConnectorRequestRecord[] {
  return [
    {
      id: "REQ-9001",
      systemName: "UIDAI Aadhaar Registry",
      systemKey: "identity",
      status: "ONLINE",
      endpoint: "https://gateway.uidai.gov.in/v2.5/ekyc",
      method: "POST",
      latencyMs: 142,
      statusCode: 200,
      applicationId: "PAN-2026-0001",
      requestPayloadSummary: '{"uid":"123456789876","consent_token":"CNS-2026-9901-SAI"}',
      responseSummary: '{"status":"SUCCESS","demographic_match":1.0,"verhoeff_valid":true}',
      timestamp: "2026-09-09T14:04:12Z",
      retryCount: 0,
    },
    {
      id: "REQ-9002",
      systemName: "DigiLocker Document Registry",
      systemKey: "document",
      status: "ONLINE",
      endpoint: "https://api.digilocker.gov.in/v3/certificate",
      method: "POST",
      latencyMs: 189,
      statusCode: 200,
      applicationId: "PAN-2026-0001",
      requestPayloadSummary: '{"doc_type":"CBSE_10TH","candidate_name":"Sai Sankeerth"}',
      responseSummary: '{"status":"FOUND","verified":true,"signature_valid":true}',
      timestamp: "2026-09-09T14:04:15Z",
      retryCount: 0,
    },
    {
      id: "REQ-9003",
      systemName: "PAN Core Deduplication Service",
      systemKey: "pan_core",
      status: "DEGRADED",
      endpoint: "https://services.incometax.gov.in/pan/v1/core",
      method: "POST",
      latencyMs: 5200,
      statusCode: 504,
      applicationId: "PAN-2026-0002",
      requestPayloadSummary: '{"applicant":"Anjali Sharma","aadhaar":"889977665544"}',
      responseSummary: "Gateway Timeout (504): Target node did not respond within deadline.",
      timestamp: "2026-09-09T14:16:30Z",
      retryCount: 1,
    },
  ];
}
